Even/config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :eventos
  resources :usuarios, only: [:create, :new]
  root 'welcome#index'
end

Even/app/models/evento.rb
class Evento < ActiveRecord::Base
	belongs_to :usuario
	geocoded_by :address
	after_validation :geocode
end

Even/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_secure_password
  
  validates_uniqueness_of :email
  has_many :eventos
end

Even/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_usuario
    @current_usuario ||= Usuario.find(session[:usuario_id]) if session[:usuario_id]
  end
  helper_method :current_usuario
end

Even/app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, except: [:index,:new,:create]
  def index
    @eventos = Evento.all
  end
  def new
    @evento = Evento.new
  end
  def create
    @evento = current_usuario.eventos.new(evento_params)
    if @evento.save
      redirect_to eventos_path, notice: "Evento creado"
    else
      render :new
    end
  end
  def show
      @hash = Gmaps4rails.build_markers(@evento) do |evento, marker|
      marker.lat evento.latitude
      marker.lng evento.longitude
      end
  end

  private
    def set_evento
      @evento = Evento.find(params[:id])
    end
    def evento_params
      params.require(:evento).permit(:name,:address,:fecha,:desc,:latitude,:longitude)
    end
end

Even/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    usuario = Usuario.find_by_email(params[:email])
      # If the user exists AND the password entered is correct.
      if usuario && usuario.authenticate(params[:password])
        # Save the user id inside the browser cookie. This is how we keep the user
        # logged in when they navigate around our website.
        session[:usuario_id] = usuario.id
        redirect_to root_url, notice: "Logged in"
      else
      # If user's login doesn't work, send them back to the login form.
        flash.now.alert = "Email or password is incorrect"
        render :new
      end
  end
  def destroy
    session[:usuario_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

Even/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
    @usuario = Usuario.new
  end
  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      session[:usuario_id] = @usuario.id
      redirect_to root_url, notice: "Thank you for sign"
    else
      render :new
    end
  end

  private
    def usuario_params
      params.require(:usuario).permit(:name,:email,:password,:password_confirmation,:tipo)
    end
end

Even/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Even/app/helpers/application_helper.rb
module ApplicationHelper
end

Even/app/helpers/eventos_helper.rb
module EventosHelper
end

Even/app/helpers/sessions_helper.rb
module SessionsHelper
end

Even/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

Even/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Even/app/views/eventos/index.html.erb
<div class="container">
<ul class="collapsible popout" data-collapsible="accordion">
  <% @eventos.each do |evento|%>
   <li>
     <div class="collapsible-header">
       <br>
       <div class="row">
         <div class="col s1 m1 l1"><img class="img-responsive circle" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt=""></div>
         <div class="col s6 offset-s1">
           <div class="row">
             <div clas="col l2"><h5><%= evento.name %></h5></div>
             <h6>Organizador</h6>
             45<span class="red-text text-red"><i class="material-icons">favorite</i></span>
           </div>
         </div>
       </div>
     </div>
     <div class="collapsible-body"><p><%= evento.desc %></p></div>
   </li>
   <%end%>
 </ul>
</div>
<div class="container">
  <div class="timeline">
    <% @eventos.each do |evento|%>
      <div class="timeline-event">
        <div class="card timeline-content">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="https://images.unsplash.com/photo-1474899452492-5eea44100ec4?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&s=e878760b7ff15f6fae02bcfeebd12320">
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= link_to evento.name, evento %><i class="material-icons right">more_vert</i></span>
          </div>
          <div class="card-action">
            <%= evento.desc %>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
            <p>Here is some more information about this product that is only revealed once clicked on.</p>
          </div>
        </div>
        <div class="timeline-badge blue white-text"><i class="material-icons">language</i></div>
      </div>
      <%end%>
  </div>
</div>
<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>
<style type="text/css">
.timeline {
position: relative;
}

.timeline .timeline-event {
position: relative;
padding-top: 5px;
padding-bottom: 5px;
}

.timeline .timeline-event .timeline-content {
position: relative;
width: calc(50% - 50px);
}

.timeline .timeline-event::before {
display: block;
content: "";
width: 2px;
height: calc(50% - 30px);
position: absolute;
background: #d2d2d2;
left: calc(50% - 1px);
top: 0;
}

.timeline .timeline-event::after {
display: block;
content: "";
width: 2px;
height: calc(50% - 30px);
position: absolute;
background: #d2d2d2;
left: calc(50% - 1px);
top: calc(50% + 30px);
}

.timeline .timeline-event:first-child::before {
display: none;
}

.timeline .timeline-event:last-child::after {
display: none;
}

.timeline .timeline-event:nth-child(even) .timeline-content {
margin-left: calc(50% + 50px);
}

.timeline .timeline-event:nth-child(odd) .timeline-content {
margin-left: 0;
}

.timeline .timeline-badge {
display: block;
position: absolute;
width: 40px;
height: 40px;
background: #d2d2d2;
top: calc(50% - 20px);
right: calc(50% - 20px);
border-radius: 50%;
text-align: center;
cursor: default;
}

.timeline .timeline-badge i {
font-size: 25px;
line-height: 40px;
}

@media (max-width: 600px) {
.timeline .timeline-event .timeline-content {
  width: calc(100% - 70px);
}
.timeline .timeline-event::before {
  left: 19px;
}
.timeline .timeline-event::after {
  left: 19px;
}
.timeline .timeline-event:nth-child(even) .timeline-content {
  margin-left: 70px;
}
.timeline .timeline-event:nth-child(odd) .timeline-content {
  margin-left: 70px;
}
.timeline .timeline-badge {
  left: 0;
}
}
</style>

Even/app/views/eventos/new.html.erb
<div class="container">
  <h1>Nuevo Evento</h1>
    <%= form_for @evento do |f| %>
      <% if @evento.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <%= @evento.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
        </ul>
      </div>
      <% end %>

      <div class="row">
        <div class="input-field col s12 m6 l6">
          <i class="material-icons prefix">account_circle</i>
          <%= f.text_field :name%>
        </div>
        <div class="input-field col s12 m6 l6">
        <i class="material-icons prefix">location_on</i>
        <%= f.text_field :address, placeholder: "Carrera 65 # 85:90, Barranquilla - Atlántico, Colombia" %>
          </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m12 l12">
          <i class="material-icons prefix">today</i>
        <%= f.text_field :fecha , placeholder: "dd-mm-aaaa"%>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m12 l12">
          <i class="material-icons prefix">info</i>
        <%= f.text_field :desc %>
        </div>
      </div>
      <div class="field" hidden>
        <%= f.label :latitude %><br />
        <%= f.text_field :latitude %>
      </div>
      <div class="field" hidden>
        <%= f.label :longitude %><br />
        <%= f.text_field :longitude %>
      </div>
      <div class="actions waves-effect waves-ligh green white-text text-white btn"><i class="material-icons right">done</i><%= f.submit %></a></div>
      <% end %>
  </div>

Even/app/views/eventos/show.html.erb
<div class="row">
        <div class="col s12 m12">
          <div class="card big">
            <div class="card-image">
              <img src="https://images.unsplash.com/photo-1470259628879-b26711784142?dpr=1&auto=format&fit=crop&w=767&h=511&q=80&cs=tinysrgb&crop=">
            <span class="card-title"><h2><%= @evento.name%></h2></span>
            </div>
            <div class="card-content">
              <ul class="collection">
                <!--
                Este es el coleccion
                -->
                <li class="collection-item avatar">
                  <img src="https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/13006526_589627404529073_4153293944546264358_n.jpg?oh=0f626a2daeee87b5b4e85d9811583251&oe=58CAF1C1" alt="" class="circle">
                  <span class="title">Organizador: <%= @evento.usuario.name %></span>
                  <a href="#!" class="secondary-content"><i class="material-icons">search</i></a>
                </li>
                <li class="collection-item avatar">
                  <i class="material-icons circle blue">location_on</i>
                  <span class="title">Dirección:  <br><%= @evento.address %></span>

                    <div style='width: 800px;'>
                      <div id="map" style='width: 800px; height: 400px;'></div>
                    </div>
                </li>
                <li class="collection-item avatar">
                  <i class="material-icons circle red">info</i>
                  <span class="title">Descripción: </span>
                  <p><%= @evento.desc %>
                  </p>
                </li>
                <li class="collection-item avatar">
                  <i class="material-icons circle yellow">stars</i>
                  <span class="title">Puntuación</span>
                  <div align="center"><i class="material-icons">grade</i>
                    <i class="material-icons">grade</i>
                    <i class="material-icons">grade</i>
                    <i class="material-icons">grade</i>
                  </div>
                  <p align="center">4/5</p>
                </li>
              </ul>
            </div>
            <div class="card-action">
              <a class="waves-effect waves-light btn">Asistir</a>
            </div>
          </div>
        </div>
      </div>
<script src="//maps.google.com/maps/api/js?key=AIzaSyAM1FOUpBoVbRjCsBbqIQFXfaoRzl7wD8o"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

Even/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Even</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/navigation"%>
<%= yield %>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</body>
</html>

Even/app/views/partials/_navigation.html.erb
<div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>

</div>

<!--Navigation-->
 <div class="navbar-fixed">
    <nav class="blue" role="navigation">
        <div class="container">
            <div class="nav-wrapper">
              <a id="logo-container" href="/" class="brand-logo center">Eventuality</a>
                <ul class="left hide-on-med-and-down">
                    <li><a href="#intro">Servicios</a></li>
                    <li><a href="#work">Trabajos</a></li>
                    <li><a href="#team">Equipo</a></li>
                    <li><a href="#contact">Contacto</a></li>
                </ul>
                <ul class="right hide-on-med-and-down">
                  <%  if current_usuario %>
                        <%  if current_usuario.tipo == 2 %>
                            <li><%= current_usuario.name %></li>
                            <li><%= link_to "Mis Eventos", eventos_path %></li>
                            <li><%= link_to "Crear Evento", new_evento_path %></li>
                            <li><%= link_to "Log out", session_path("current"), method: "delete" %></li>
                        <% else %>
                            <li><%= current_usuario.name %></li>
                            <li><%= link_to "Eventos", eventos_path %></li>
                            <li><%= link_to "Log out", session_path("current"), method: "delete" %></li>
                        <% end %>
                  <% else %>
                          <li><%= link_to "Sign up", new_usuario_path %></li>
                          <li><%= link_to "Log In", new_session_path %></li>
                          <li><a href="collapsible.html">JavaScript</a></li>
                <% end %>
                </ul>
            </div>
        </div>
    </nav>
  </div>

Even/app/views/usuarios/new.html.erb
<div class="container">
  <h1>Sign Up</h1>
    <%= form_for @usuario do |f| %>
      <% if @usuario.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <%= @usuario.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
        </ul>
      </div>
      <% end %>

      <div class="row">
        <div class="input-field col s12 m6 l6">
          <i class="material-icons prefix">account_circle</i>
          <%= f.text_field :name, placeholder: "Juanito", type: "text", class: "validate" %>
        </div>
        <div class="input-field col s12 m6 l6">
    	    <input placeholder="Perez" type="text" class="validate">
          <label for="first_name"></label>
    	  </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m12 l12">
          <i class="material-icons prefix">email</i>
          <%= f.text_field :email, placeholder: "email@company.com", type: "text", class: "validate" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m6 l6">
          <%= f.text_field :password, placeholder: "Password", type: "password", class: "validate" %>
        </div>
        <div class="input-field col s12 m6 l6">
          <%= f.text_field :password_confirmation, placeholder: "Confirm password", type: "password", class: "validate" %>
        </div>
      </div>
      <div class="field" hidden>
        <%= f.label :tipo %><br />
        <%= f.text_field :tipo, value: 1%>
      </div>
            <h1>Seleccione sus gustos</h1>

      ⁠⁠⁠<div class="container">
    <div class="row">
        <div class="col s4" style="  width: 400px;">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="https://images.unsplash.com/photo-1430232324554-8f4aebd06683?dpr=1&auto=format&fit=crop&w=767&h=431&q=80&cs=tinysrgb&crop=" height="200" width="200">
                    <span class="card-title">Deportes</span>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
                    <h4>Seleccionado</h4>
                </div>
            </div>
        </div>
        <div class="col s4" style="width: 400px;">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="https://images.unsplash.com/photo-1435034568314-8303dbda4b8c?dpr=1&auto=format&fit=crop&w=767&h=510&q=80&cs=tinysrgb&crop=" height="200" width="200">
                    <span class="card-title">Cultura</span>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
                    <h4>Seleccionado</h4>
                </div>
            </div>
        </div>
        <div class="col s4" style="width: 400px;">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="https://images.unsplash.com/photo-1416273567255-8abe875affcd?dpr=1&auto=format&fit=crop&w=767&h=575&q=80&cs=tinysrgb&crop=" height="200" width="200">
                    <span class="card-title">Musica</span>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
                    <h4>Seleccionado</h4>
                </div>
            </div>
        </div>
        <div class="col s4" style="width: 400px;">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator"         src="https://images.unsplash.com/photo-1457734933360-81bb2e6ed002?dpr=1&auto=format&fit=crop&w=767&h=512&q=80&cs=tinysrgb&crop=" height="200" width="200">
                    <span class="card-title">Cine</span>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
                    <h4>Seleccionado</h4>
                </div>
            </div>

        <!--Aqui termina la linea-->
      </div>
      <div class="actions waves-effect waves-ligh green white-text text-white btn"><i class="material-icons right">done</i><%= f.submit %></a></div>
      <div class="waves-effect waves-ligh red btn"><i class="material-icons right">clear</i><%= link_to "Cancelar", root_path, class: "white-text text-white"%></div>
      <% end %>

  </div>